// Code generated by esodmgen; DO NOT EDIT.
package models

import (
	esodm "github.com/ctolon/esodm"
)

// ProductFields contains typed descriptors for Product's JSON fields.
var ProductFields = struct {
	CreatedAt esodm.DateField
	Location  esodm.GeoField
	Name      esodm.TextField
	Price     esodm.OrderedField[int]
	Reviews   struct {
		esodm.ObjectField
		Rating esodm.OrderedField[int]
		Text   esodm.TextField
	}
	UpdatedAt esodm.DateField
}{
	CreatedAt: esodm.Date("created_at"),
	Location:  esodm.Geo("location"),
	Name:      esodm.Text("name"),
	Price:     esodm.OrderedValue[int]("price"),
	Reviews: struct {
		esodm.ObjectField
		Rating esodm.OrderedField[int]
		Text   esodm.TextField
	}{
		ObjectField: esodm.Object("reviews"),
		Rating:      esodm.OrderedValue[int]("reviews.rating"),
		Text:        esodm.Text("reviews.text"),
	},
	UpdatedAt: esodm.Date("updated_at"),
}
