// esodmgen generates typed field descriptors from struct declarations.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/build"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const header = "// Code generated by esodmgen; DO NOT EDIT.\n"

func main() {
	types := flag.String("type", "", "comma-separated struct names")
	output := flag.String("output", "esodm_fields.gen.go", "output Go file")
	dir := flag.String("dir", ".", "model directory")
	flag.Parse()
	if err := run(*dir, *types, *output); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func run(dir, names, output string) error {
	if names == "" {
		return fmt.Errorf("-type is required")
	}
	if filepath.Base(output) != output || !strings.HasSuffix(output, ".go") {
		return fmt.Errorf("-output must be a Go filename")
	}
	path := filepath.Join(dir, output)
	if prior, err := os.ReadFile(path); err == nil && !bytes.HasPrefix(prior, []byte(header)) {
		return fmt.Errorf("refusing to overwrite non-generated file %s", path)
	} else if err != nil && !os.IsNotExist(err) {
		return err
	}
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	var files []*ast.File
	packageName := ""
	for _, entry := range entries {
		filename := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(filename, ".go") || strings.HasSuffix(filename, "_test.go") || filename == output {
			continue
		}
		matches, err := build.Default.MatchFile(dir, filename)
		if err != nil {
			return err
		}
		if !matches {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, filename), nil, parser.ParseComments|parser.SkipObjectResolution)
		if err != nil {
			return err
		}
		if packageName != "" && packageName != file.Name.Name {
			return fmt.Errorf("expected one package")
		}
		packageName = file.Name.Name
		files = append(files, file)
	}
	if len(files) == 0 {
		return fmt.Errorf("expected one package")
	}
	declarations, used, err := generateDescriptors(dir, fset, files, names, packageName)
	if err != nil {
		return err
	}
	var source bytes.Buffer
	source.WriteString(header)
	fmt.Fprintf(&source, "package %s\nimport (\n", packageName)
	aliases := []string{}
	for alias := range used {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)
	for _, alias := range aliases {
		fmt.Fprintf(&source, "%s %q\n", alias, used[alias])
	}
	source.WriteString(")\n")
	source.Write(declarations.Bytes())
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return err
	}
	temp, err := os.CreateTemp(dir, ".esodmgen-*.go.tmp")
	if err != nil {
		return err
	}
	defer func() { _ = os.Remove(temp.Name()) }()
	if _, err = temp.Write(formatted); err != nil {
		_ = temp.Close()
		return err
	}
	if err = temp.Chmod(0644); err != nil {
		_ = temp.Close()
		return err
	}
	if err = temp.Close(); err != nil {
		return err
	}
	return os.Rename(temp.Name(), path)
}
