// Code generated by esodmgen; DO NOT EDIT.
package main

import (
	esodm "github.com/ctolon/esodm"
)

// ProductFields contains typed descriptors for Product's JSON fields.
var ProductFields = struct {
	Name    esodm.TextField
	Price   esodm.OrderedField[int]
	Related esodm.RelationField[Product]
	Reviews struct {
		esodm.ObjectField
		Stars esodm.OrderedField[int]
		Text  esodm.TextField
	}
}{
	Name:    esodm.Text("name"),
	Price:   esodm.OrderedValue[int]("price"),
	Related: esodm.Relation[Product]("related"),
	Reviews: struct {
		esodm.ObjectField
		Stars esodm.OrderedField[int]
		Text  esodm.TextField
	}{
		ObjectField: esodm.Object("reviews"),
		Stars:       esodm.OrderedValue[int]("reviews.stars"),
		Text:        esodm.Text("reviews.text"),
	},
}
